# Generated by Django 4.0.3 on 2024-01-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_api', '0002_bin_alter_location_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
