# Generated by Django 4.0.3 on 2023-10-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='name',
        ),
        migrations.AddField(
            model_name='shoes',
            name='color',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='manufacturer',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='model_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
