# Generated by Django 5.0.1 on 2024-01-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "shoes_rest",
            "0004_remove_shoes_name_shoes_color_shoes_manufacturer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoes",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
